# Generated by Django 3.1.1 on 2020-09-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=50)),
                ('full_title', models.CharField(db_index=True, max_length=100)),
                ('alt_titles', models.CharField(db_index=True, max_length=350, verbose_name='alternative titles')),
                ('rating', models.CharField(default='0.0', max_length=4)),
                ('cover_url', models.URLField(verbose_name='cover image url')),
                ('directors', models.CharField(max_length=150)),
                ('screenwriters', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=40)),
                ('official_site', models.URLField()),
                ('prod_region', models.CharField(max_length=40)),
                ('language', models.CharField(max_length=50)),
                ('premiere_dates', models.CharField(max_length=80)),
                ('length', models.CharField(max_length=120)),
                ('imdb', models.SlugField(db_index=False, max_length=10)),
                ('year', models.CharField(max_length=6)),
                ('synopsis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=70)),
                ('fullname', models.CharField(db_index=True, max_length=40)),
                ('douban_url', models.URLField()),
                ('sex', models.CharField(max_length=1)),
                ('horoscope', models.CharField(max_length=3)),
                ('birth_date', models.CharField(max_length=10)),
                ('birth_place', models.CharField(max_length=38)),
                ('careers', models.CharField(max_length=30)),
                ('other_names', models.CharField(max_length=300)),
                ('family', models.CharField(max_length=200)),
                ('imdb', models.SlugField(db_index=False, max_length=10)),
                ('introduction', models.TextField()),
                ('photo_url', models.URLField()),
                ('films', models.ManyToManyField(to='movie.Film')),
                ('screen_partners', models.ManyToManyField(to='movie.Actor')),
            ],
        ),
    ]
