# Generated by Django 3.1.1 on 2020-09-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200910_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='website_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
